### PR TITLE
Added support for Linea Micra

### PR DESCRIPTION
**Pull request by zweckj**
This PR brings support for the Micra. Fixing #35 
Bringing my fork to main repositories dev branch, to enable testing and fixing support for the existing machines, before merging to main.
- added a class interface.py which relays between lmcloud and lmdirect
- lmcloud is initialized in cloud only mode once to get a connection to LaMarzocco and get the model name so we can decide whether to init lmdirect or lmcloud
- added Micra to entities
- changed api.py to inherit from the interface, interface is now initialized by classmethod instead of init
- fixed zeroconf to support "sn" attribute provided by Micra

### CODE REVIEW

**Comment by zweckj** [comment]
Hey @rccoleman just checking in about this PR with you.

**Comment by ayn** [comment]
@zweckj hi, did the latest gateway update break this for you too? I'm at `V3.1-RC4` gateway and `1.17` machine firmware, and it doesn't seem to be working anymore.

**Comment by zweckj** [comment]
@ayn which machine are we talking about? For Mini and Micra you can try the latest release in my fork https://github.com/zweckj/lamarzocco

**Comment by ayn** [comment]
@zweckj micra. Will pull the latest and give it a try. Thanks!

**Comment by ayn** [comment]
@zweckj working great now, thanks!

**Comment by zweckj** [comment]
abandoning this PR, as it would be too much work to test this with the old & new API simultaneously, while the old API is being deprecated. Working on a re-write which is cloud only.

**Pull request closed without merging**
