### PR TITLE
Moving to lmcloud

### PR DESCRIPTION
**Pull request by zweckj**
sorry, cleaned up my branches and closed the original PR in the process

### CODE REVIEW

**Comment by zweckj** [comment]
Should we merge or did you find issues @rccoleman ?

**Comment by rccoleman** [comment]
I'm seeing some issues with the service calls when I use my Lovelace cards that I need to dig into. For instance, I'm getting this when I try to change the dose for one of the buttons:

```
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/config/custom_components/lamarzocco/services.py", line 87, in set_dose
    await call_service(lm.set_dose, key=key, pulses=pulses)
  File "/config/custom_components/lamarzocco/services.py", line 38, in call_service
    raise HomeAssistantError(ex) from ex
homeassistant.exceptions.HomeAssistantError: Request to endpoint https://gw-lmz.lamarzocco.io/v1/home/machines/xxx/dose failed with status code 500
```

I was also seeing this when I try to adjust the auto on/off time (specifically, off for Saturday):

```
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/config/custom_components/lamarzocco/services.py", line 70, in set_auto_on_off_times
    await call_service(
  File "/config/custom_components/lamarzocco/services.py", line 38, in call_service
    raise HomeAssistantError(ex) from ex
homeassistant.exceptions.HomeAssistantError: list index out of range
```

I'll try to take a look today, but are the auto on/off calls working for you?

**Comment by zweckj** [comment]
implemented both findings, for the day on the schedule I'm now always shortening to [0:3] so it doesn't matter if you put in the full day or the 3 letters only. Adapted the API call on the doses side. beta.9 should include those changes.

**Comment by zweckj** [comment]
> Why they decided to make the keys arbitrarily different for the request and response, I have no idea

no idea either. Before GW v3 the keys in the object returned form the remote config call was all upper case while the one from the local endpoint were camel cased... I don't think they are the greatest developers...

**Comment by rccoleman** [comment]
The auto on/off enable flags appear to be mutually exclusive now, like a radio button.

**Comment by zweckj** [comment]
beta.10 should fix the "radio button" issue

**Comment by zweckj** [comment]
image
Unrelated to this PR, but just tested the cards and they don't look very pretty if you  don't have 4 keys...

**Comment by rccoleman** [comment]
Yes, I noticed that when they removed the fifth button for continuous flow. I'll fix it.

**Comment by rccoleman** [comment]
I was finally able to update my machine to v3.1-RC6 (they must stage these deployments) and the preinfusion numbers look and act right in the official app now.  There's something broken in the translation between the values and the attributes in the integration, though.  The values that should be for preinfusion are reflected in the prebrewing "stop" times, and I get all zeroes for preinfusion.

Prebrewing/preinfusion are differentiated by different "modes" (`TypeA` == prebrewing, `TypeB` == preinfusion) and it looks like the `preWetHoldTime` becomes the "preinfusion time" when the mode is `TypeB` (`preWetTime` is just zero for me).  The old gateway held different values for prebrew/preinfusion in different memory locations, and maybe this one does internally as well, but they seem to have overloaded the `preinfusionSettings` dict entries to represent both in the API.

**Comment by zweckj** [comment]
> The values that should be for preinfusion are reflected in the prebrewing "stop" times, and I get all zeroes for preinfusion.

I just checked and the vaues were parsed correctly for both preinfusion and prebrew, I was just overloading the values as well, so when you were in preinfusion you were seeing the preinfusion values combined with zero in prebrew. I changed that behavior in beta.11, so you should now only see the values which are currently relevant with the rest being zeroes.

**Comment by zweckj** [comment]
@rccoleman is it ok now? Did you stumble upon any other issues?

**Comment by rccoleman** [comment]
I updated to 2023.8.0 beta yesterday and I'm now seeing a bunch of these show up.  I was planning to investigate and haven't gotten around to it yet:

```
2023-07-27 16:14:57.655 ERROR (MainThread) [homeassistant.components.switch] Ignoring invalid device info: Invalid device info {'default_name': 'La Marzocco GS3 AV', 'identifiers': {('lamarzocco', 'xx')}, 'manufacturer': 'La Marzocco', 'model': 'GS3 AV', 'name': 'xxx', 'sw_version': '1.40'} for 'lamarzocco' config entry: device info needs to either describe a device, link to existing device or provide extra information.
```

**Comment by zweckj** [comment]
> I updated to 2023.8.0 beta yesterday and I'm now seeing a bunch of these show up. I was planning to investigate and haven't gotten around to it yet:
> 
> ```
> 2023-07-27 16:14:57.655 ERROR (MainThread) [homeassistant.components.switch] Ignoring invalid device info: Invalid device info {'default_name': 'La Marzocco GS3 AV', 'identifiers': {('lamarzocco', 'xx')}, 'manufacturer': 'La Marzocco', 'model': 'GS3 AV', 'name': 'xxx', 'sw_version': '1.40'} for 'lamarzocco' config entry: device info needs to either describe a device, link to existing device or provide extra information.
> ```

I haven't had time to test it, but judging by this code https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/device_registry.py#L159 they are testing if the device info is a subset of 3 defined device info types. I removed the `default_name` from our device info in beta.12 and hopefully that should fix it

**Comment by zweckj** [comment]
@rccoleman are you using the `state_attributes` on the water heaters somewhere? I removed those in the latest beta as those appear to be non-standard

**Comment by zweckj** [comment]
Imo we should put a release on your repo soon, because there are probably still people with a broken integration and more and more people are moving to my repo which is suboptimal

**Comment by zweckj** [comment]
@rccoleman did you have the chance to check your 403 issue with the newest beta? Also, Minis don't appear to be affected, this seems limited to GS3s...

**Comment by rccoleman** [comment]
Not yet, been super busy at work this week.

**Comment by rccoleman** [comment]
Unfortunately, I'm still seeing the 403s and `2023-08-13 18:21:16.445 WARNING (MainThread) [lmcloud.lmcloud] Could not connect to local API although initialized` with the latest beta.  I didn't have a Bluetooth connection on my HA box at all, so I also set up a Bluetooth Proxy node (Olimex) and I suppose it's working.  Still, doesn't seem to help.  I'll keep trying to dig into what's going on.

**Comment by zweckj** [comment]
> I suppose it's working.  Still, doesn't seem to help.  I'll keep trying to dig into what's going on.

Do you see in the logs that it does try to connect with Bluetooth? If I can't find Bluetooth adapters I'm not initializing BT.

**Comment by rccoleman** [comment]
Yep:

```
2023-08-13 21:41:43.226 DEBUG (MainThread) [custom_components.lamarzocco.lm_client] Model name: GS3 AV
2023-08-13 21:41:43.226 DEBUG (MainThread) [custom_components.lamarzocco.lm_client] Found bluetooth adapters, initializing with bluetooth.
2023-08-13 21:41:43.226 DEBUG (MainThread) [custom_components.lamarzocco.lm_client] Connecting to machine with Bluetooth.
2023-08-13 21:41:43.642 DEBUG (MainThread) [custom_components.lamarzocco.lm_client] Initializing local API. 
2023-08-13 21:41:43.642 DEBUG (MainThread) [lmcloud.lmcloud] Getting config from local API.
2023-08-13 21:41:43.770 WARNING (MainThread) [lmcloud.lmcloud] Could not connect to local API although initialized
2023-08-13 21:41:43.771 DEBUG (MainThread) [lmcloud.lmcloud] Full error: Querying local API failed with statuscode: 403
2023-08-13 21:41:44.055 DEBUG (MainThread) [lmcloud.lmcloud] Getting statistics from cloud.
```

**Comment by zweckj** [comment]
Huh. Really thought that must be it. Either BT authentication is working differently for your machine or they're enabling the local API somewhere else.

**Comment by zweckj** [comment]
@rccoleman regardless of that issue for the GS3s, what's your plan for this PR? I suspect 99% of the users updated their machines already and the this release isn't working for them anymore? Do you plan on closing it, or deprecate this repo?

**Comment by rccoleman** [comment]
I'm thinking about just deprecating this repo, as there really isn't much of my code left. It's just a completely different way to interact with the service, which demands a new methodology. I'm happy to keep mine around for folks who haven't updated their machines and don't use the app, but I don't even know if that will survive the expiration date in the next few weeks. I suggest having folks migrate to your repo, if you're okay with that, and I'll contribute what and when I can.

**Comment by zweckj** [comment]
Fine for me, but then I'll disconnect my repo from yours to allow issues to be opened on mine directly and I will update the default repo for HACS. 
Also, you maybe should put out a release which makes people aware in the release notes that an update won't be coming and they need to migrate manually. 
Also, I'd love if you'd continue contributing, especially to solve problems for your machine. 
Btw. I'm not sure I ever thanked you for your work and help. You and your integration helped me getting into HA development and I couldn't have done it without your initial hints 😊

**Pull request closed without merging**
