### PR TITLE
Moving over to LMCloud API

### PR DESCRIPTION
**Pull request by zweckj**
> **Warning**
> Do not merge to main yet, WIP

This is the "re-write" I'm working on I mentioned in #43. Just opening that PR to notify you about it @rccoleman and to have a place for discussions. It is not yet properly tested and I will probably add additional functionality (options flow, optional enabling of the WebSocket API to get the shot timer)
Notable changes:
- lmdirect removed entirely
- LaMarzocco class renamed to LaMarzoccoClient, inherits only from LmCloud
- polling is moved entirely to Data Coordinator
- moved more of the setup to the entity-base
- added HA re-auth functionality

### CODE REVIEW

**Comment by rccoleman** [comment]
I updated my GS3 AV this morning, added it to LM_CLOUD_MODELS, and it seems to be working well for my machine (at least setup, temp reporting, and on/off).  First reaction is that the rest of the keys need to be supported for the GS3_AV (1-4) for dose, prebrew, and preinfusion, and that almost all of the attributes are gone (schedule, drinks, auto on/off, preinfusion, etc.).  I'm poking through the code to see if I missed adding a model somewhere, but you may know better.  For what it's worth, here's what I get from the local config API:

```
{
    "version": "v1",
    "preinfusionModesAvailable": [
        "ByDoseType"
    ],
    "machineCapabilities": [
        {
            "family": "GS3AV",
            "groupsNumber": 1,
            "coffeeBoilersNumber": 1,
            "hasCupWarmer": false,
            "steamBoilersNumber": 1,
            "teaDosesNumber": 1,
            "machineModes": [
                "BrewingMode",
                "StandBy"
            ],
            "schedulingType": "weeklyScheduling"
        }
    ],
    "machine_sn": "xxx",
    "machine_hw": "2",
    "isPlumbedIn": true,
    "isBackFlushEnabled": false,
    "standByTime": 0,
    "tankStatus": true,
    "groupCapabilities": [
        {
            "capabilities": {
                "groupType": "AV_Group",
                "groupNumber": "Group1",
                "boilerId": "CoffeeBoiler1",
                "hasScale": false,
                "hasFlowmeter": true,
                "numberOfDoses": 4
            },
            "doses": [
                {
                    "groupNumber": "Group1",
                    "doseIndex": "DoseA",
                    "doseType": "PulsesType",
                    "stopTarget": 135
                },
                {
                    "groupNumber": "Group1",
                    "doseIndex": "DoseB",
                    "doseType": "PulsesType",
                    "stopTarget": 97
                },
                {
                    "groupNumber": "Group1",
                    "doseIndex": "DoseC",
                    "doseType": "PulsesType",
                    "stopTarget": 108
                },
                {
                    "groupNumber": "Group1",
                    "doseIndex": "DoseD",
                    "doseType": "PulsesType",
                    "stopTarget": 121
                }
            ],
            "doseMode": {
                "groupNumber": "Group1",
                "brewingType": "PulsesType"
            }
        }
    ],
    "machineMode": "BrewingMode",
    "teaDoses": {
        "DoseA": {
            "doseIndex": "DoseA",
            "stopTarget": 8
        }
    },
    "boilers": [
        {
            "id": "SteamBoiler",
            "isEnabled": true,
            "target": 123.90000152587891,
            "current": 123.80000305175781
        },
        {
            "id": "CoffeeBoiler1",
            "isEnabled": true,
            "target": 95,
            "current": 96.5
        }
    ],
    "boilerTargetTemperature": {
        "SteamBoiler": 123.90000152587891,
        "CoffeeBoiler1": 95
    },
    "preinfusionMode": {
        "Group1": {
            "groupNumber": "Group1",
            "preinfusionStyle": "PreinfusionByDoseType"
        }
    },
    "preinfusionSettings": {
        "mode": "TypeB",
        "Group1": [
            {
                "groupNumber": "Group1",
                "doseType": "DoseA",
                "preWetTime": 0.5,
                "preWetHoldTime": 1
            },
            {
                "groupNumber": "Group1",
                "doseType": "DoseB",
                "preWetTime": 0.5,
                "preWetHoldTime": 1
            },
            {
                "groupNumber": "Group1",
                "doseType": "DoseC",
                "preWetTime": 3.2999999523162842,
                "preWetHoldTime": 3.2999999523162842
            },
            {
                "groupNumber": "Group1",
                "doseType": "DoseD",
                "preWetTime": 2,
                "preWetHoldTime": 2
            }
        ]
    },
    "weeklySchedulingConfig": {
        "enabled": true,
        "monday": {
            "enabled": true,
            "h_on": 6,
            "h_off": 16,
            "m_on": 0,
            "m_off": 0
        },
        "tuesday": {
            "enabled": true,
            "h_on": 6,
            "h_off": 16,
            "m_on": 0,
            "m_off": 0
        },
        "wednesday": {
            "enabled": true,
            "h_on": 6,
            "h_off": 16,
            "m_on": 0,
            "m_off": 0
        },
        "thursday": {
            "enabled": true,
            "h_on": 6,
            "h_off": 16,
            "m_on": 0,
            "m_off": 0
        },
        "friday": {
            "enabled": true,
            "h_on": 6,
            "h_off": 16,
            "m_on": 0,
            "m_off": 0
        },
        "saturday": {
            "enabled": true,
            "h_on": 6,
            "h_off": 16,
            "m_on": 0,
            "m_off": 0
        },
        "sunday": {
            "enabled": true,
            "h_on": 6,
            "h_off": 16,
            "m_on": 0,
            "m_off": 0
        }
    },
    "clock": "1901-07-08T10:29:00",
    "firmwareVersions": [
        {
            "name": "machine_firmware",
            "fw_version": "1.40"
        },
        {
            "name": "gateway_firmware",
            "fw_version": "v3.1-rc4"
        }
    ]
}
```
My custom Lovelace cards expect to find the attributes, so they're all currently broken.  I'll poke around some more.

**Comment by zweckj** [comment]
To support the doses `lmcloud` needs an update as I'm not parsing those (up until now, there was nothing of value in there). The attributes might have always been broken I never paid attention to those to be honest. That the pre-infusion settings are weird in the app I noticed as well for my machine.

**Comment by zweckj** [comment]
The extra args I remember I saw that code, wasn't quite sure what the expected outcome is there, so I ignored it 😅

**Comment by rccoleman** [comment]
My goal with the lmdirect library was to pull all the data, sometimes with a conversion, into a big dict and then let the integration sort out what's displayed and what goes where.  That's where the entity definitions and attribute maps come in, based on shared key names between the library and integration.  Changing the library is a pain, so I wanted to err on the side of collecting too much information and giving the integration more flexibility in what to do.

As far as displaying the attributes is concerned, showing the auto on/off schedule that you want to change, for instance, seemed important :).

**Comment by zweckj** [comment]
> My goal with the lmdirect library was to pull all the data, sometimes with a conversion, into a big dict

I figured that out and replicated it somewhat (you will find the current_status dict at the top of `lmcloud.py`, but I only translated some of the config to the dict (those properties I figured I'd need), as I thought a have a dict with the whole json anyways.

> As far as displaying the attributes is concerned, showing the auto on/off schedule that you want to change, for instance, seemed important :).

You're not wrong there. I just never use that feature, but schedule through HA automations, so I didn't really think about that.

> BTW, the local Bluetooth integration seems useful if it replicates the cloud APIs. The code makes it look like you can send whatever you would otherwise send to the cloud REST API? With support for Bluetooth proxies, Bluetooth control has become a totally viable way to communicate with devices.

Kind of. Before the upgrade they only mapped a handful of endpoints to Bluetooth (the ones I have atm) the rest went through the cloud. I didn't have time to check if they mapped more things to BT now. Also, BT is a bit annoying...

Is your machine still discoverable through mDNS?

**Comment by rccoleman** [comment]
No, couldn't find anything advertised anymore.

**Comment by zweckj** [comment]
Bummer. We can maybe use Bluetooth discovery. What's your machine's name in BT?

**Comment by zweckj** [comment]
I'll be working on bringing more attributes to `lmcloud` tomorrow, but I need your help: I don't have any functions for `set_dose` or `set_dose_hot_water` at the moment, neither through cloud nor through Bluetooth. If you got time you could try to map those calls.

**Comment by rccoleman** [comment]
That took a while, but yes, the BT name is `GS3AV_GSxxx`, where the last bit is my serial number.  I'll poke around a bit.

**Comment by zweckj** [comment]
just published release v0.12.0-beta.1, which should bring back most of the attributes and also allows GS3 access to Bluetooth on `lmcloud` side. Please go ahead and test.

**Comment by zweckj** [comment]
Also I checked whether they added additional Bluetooth endpoints, but couldn't find any - maybe there are some specific to your machine, but I doubt it to be honest. Maybe only some regarding doses, but I expect that goes through the cloud as well.

**Comment by rccoleman** [comment]
The attributes look much better now, thanks.  There's actually a fifth key for the dose (what I normally think of as "continuous") that weirdly doesn't even show up in the API response.  Between that and the broken preinfusion (which is a *new* feature), this device firmware and app seem very "beta".

**Comment by zweckj** [comment]
> this device firmware and app seem very "beta".

The version is "RC4" after all 😂

**Comment by zweckj** [comment]
[v0.12.0-beta.2](https://github.com/zweckj/lamarzocco/releases/tag/v0.12.0-beta.2) should include some of the additional drink stat counters as well

**Comment by rccoleman** [comment]
A couple of fixes:

```
diff --git a/lmcloud/helpers.py b/lmcloud/helpers.py
index 3260896..d8a522e 100644
--- a/lmcloud/helpers.py
+++ b/lmcloud/helpers.py
@@ -45,14 +45,16 @@ def schedule_out_to_hass(config) -> dict:
             parsed["global_auto"] = "Enabled" if weeklySchedulingConfig[key] else "Disabled"
         else:
             day_short = key[0:3]
+            enabled   = "Enabled" if weeklySchedulingConfig[key]["enabled"] else "Disabled"
             h_on      = weeklySchedulingConfig[key]["h_on"]
             h_off     = weeklySchedulingConfig[key]["h_off"]
-            m_on      = weeklySchedulingConfig[key]["m_on"] 
+            m_on      = weeklySchedulingConfig[key]["m_on"]
             m_off     = weeklySchedulingConfig[key]["m_off"]
+            parsed[f"{day_short}_auto"] =       enabled
             parsed[f"{day_short}_on_min"] =     m_on
             parsed[f"{day_short}_off_min"] =    m_off
             parsed[f"{day_short}_on_hour"] =    h_on
-            parsed[f"{day_short}_on_hour"] =    h_off
+            parsed[f"{day_short}_off_hour"] =   h_off
             parsed[f"{day_short}_on_time"] =    str(h_on) + ":" + str(m_on).zfill(2)
             parsed[f"{day_short}_off_time"] =   str(h_off) + ":" + str(m_off).zfill(2)
```

**Comment by zweckj** [comment]
Will add it tomorrow. Did you get somewhere on the pulses setting side?

**Comment by rccoleman** [comment]
Regarding doses, the request looks like this for the fourth button (D):

`POST https://gw-lmz.lamarzocco.io/v1/home/machines/GSxxx/dose HTTP/2.0`
```
{
    "dose_index": "DoseD",
    "dose_type": "PulsesType",
    "group": "Group1",
    "value": 122
}
```
They also removed the "continuous" dose from the app, so maybe it's truly continuous now.  It used to default to "1000".

The app then requests machine status from the local API and gets this as the "dose" part:
```
            "doses": [
                {
                    "doseIndex": "DoseA",
                    "doseType": "PulsesType",
                    "groupNumber": "Group1",
                    "stopTarget": 135
                },
                {
                    "doseIndex": "DoseB",
                    "doseType": "PulsesType",
                    "groupNumber": "Group1",
                    "stopTarget": 97
                },
                {
                    "doseIndex": "DoseC",
                    "doseType": "PulsesType",
                    "groupNumber": "Group1",
                    "stopTarget": 108
                },
                {
                    "doseIndex": "DoseD",
                    "doseType": "PulsesType",
                    "groupNumber": "Group1",
                    "stopTarget": 122
                }
            ]
```

**Comment by zweckj** [comment]
> I'm most interested in the Bluetooth interface, but I haven't figured out how to query or map those calls. Is there a straightforward way to see what it supports? Clearly the app is just making cloud calls for those functions in my case.

afaik there is no straightforward way. I'm always using the XCode utilities to capture the Bluetooth traffic (for iOS) and analyze them in Wireshark.


added the doses functions in beta-3.

**Comment by zweckj** [comment]
In beta.4 I added the option to connect to the WebSocket of the machine (you need to enable it specifically in the integration's settings) giving you access to a (near) real-time sensor that shows whether you're currently brewing. I'm curious to see if it works with your machine as well.

**Comment by rccoleman** [comment]
Was the connection flaky for you this morning?  I was getting a stream of these every minute or so and the integration failed to setup, even after an HA restart and toggling the machine power on and off:

`2023-07-10 08:39:21.204 ERROR (MainThread) [custom_components.lamarzocco.coordinator] 'NoneType' object is not subscriptable`

I finally launched the official app and it initially said that it was connected "remote" with some functionality not available, and then it transitioned to green/local.  Once it did that, the HA integration was suddenly able to connect and is working fine now.  I don't know if there was a server-side issue, or if launching the iOS app somehow "unlocked" the integration in some way.

**Comment by zweckj** [comment]
No, during my morning (9 hours prior to yours) I had no problems. And now I also don’t see anything in the logs

**Comment by zweckj** [comment]
Software is definitely not LM's strength... I mean who in their right mind does a big cloud and app migration all at once, instead of repointing the DNS and doing the software migration afterwards... Today I discovered an interesting bit in the WebSocket stream called "SystemInfo" (you can find it [here](https://github.com/zweckj/lmcloud/blob/main/docs/websockets.md) if you're interested) where it sounds like the App also talks MQTT with the machine, adding a 4th protocol...

**Comment by rccoleman** [comment]
I found some juicy MQTT stuff a while ago that never came to anything: https://community.home-assistant.io/t/la-marzocco-gs-3-linea-mini-support/203581/61.  It was a cloud broker and I could connect, but it would quickly disconnect.  There's some pretty cool details in that SystemInfo call.

**Comment by zweckj** [comment]
No it doesn't appear to accept any send commands... Start a brew while having the connection open. You will get the statistics info afterwards and I also got the SystemInfo then (but only one time)

**Comment by rccoleman** [comment]
Heads up on this when I enabled websockets in the integration configuration:
```
2023-07-10 12:32:03.070 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.lamarzocco entity: binary_sensor.gs013432_brew_active
2023-07-10 12:32:05.531 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.11/asyncio/unix_events.py:110: RuntimeWarning: coroutine 'WebSocketCommonProtocol.close' was never awaited
  self._signal_handlers[sig] = handle
```

**Comment by zweckj** [comment]
yeah I noticed this as well, but tbh I don't know how to get rid of it... It doesn't do anything regarding functionality as far as I know.

**Comment by zweckj** [comment]
I'm trying to close the connection as gracefully as I can (https://github.com/zweckj/lmcloud/blob/main/lmcloud/lmlocalapi.py), if you have any ideas...

**Comment by rccoleman** [comment]
Ya got me.  It only seems to happen when I enable the websocket interface, and when I just reproed it, it was repeating every 30s.  Seems like it's related to the data update coordinator somehow.

**Comment by zweckj** [comment]
> It was repeating every 30s. Seems like it's related to the data update coordinator somehow.

Weird, for me it only happens once after a reload, or if you connect through other means to the WebSocket as well (Postman, official app), so the connection gets closed forcefully. Maybe it's the `websocket.close()` in the signal_handler that is causing that...

> Hmm, HA also hung at startup when I had websockets enabled in the config. I disabled it, restarted HA, and it came up fine.

HA comes up, it just takes quite a while. No idea what is blocking here, as the whole WebSocket thing is happening in a separate task...

**Comment by zweckj** [comment]
I don't see those anymore in beta.5

**Comment by zweckj** [comment]
with beta.6 the delayed startup issue should be gone as well, also state is updating again if WebSockets are enabled

**Comment by zweckj** [comment]
@rccoleman did you have time to check beta.6?

**Comment by rccoleman** [comment]
> @rccoleman did you have time to check beta.6?

Yes, I've had it installed since you released it and I haven't seen any issues. I haven't had websockets enabled the whole time, but I'll keep them on for now. I keep getting 'download failed' when I try to update to the v3.1-RC6 gateway firmware, so I'm still on v3.1-RC4.

**Comment by rccoleman** [comment]
I did earlier, but I just whacked them by flitering them in `recorder:` and forgot about them :)

```
  filters:
    lmcloud.lmcloud:
      - 'Using local status object'
```

I'm still seeing them with b6, but I see that you've removed that line in the latest lmcloud.  I suspect that it was because of this in `lmcloud.py:__init__()` :)

```
        _logger.setLevel(logging.DEBUG)
```

**Comment by zweckj** [comment]
Oh crap, how did I miss this?! Guess I was searching too much in HA's settings 😅 Thanks!

**Comment by zweckj** [comment]
Added a new beta, WebSockets are now opt-out instead of opt-in, this loglevel part is removed from lmcloud and I made getting the values from the dictionaries more reliable in there. 
I also updated the documentation to reflect some of the changes. Client ID and secret have changed with the Micra, I extracted the new values from the Android APK (which do match the ones I discovered through mitmproxy) and set them as default during the initial config flow.

**Pull request closed without merging**
