### PR TITLE
Detect when the water reservoir is empty (Linea Mini)

### PR DESCRIPTION
**Pull request by timclipsham**
Hey @rccoleman, I've put together a change across this repo and `rccoleman/lmdirect` to add support for detection when the Linea Mini water tank has run out of water so in HA I can send myself an alert to fill the tank. As I don't have a GS3 I can't confirm if the detection also works there, so I've limited it to just the Linea Mini. If you're not happy with the changes, please feel free to critique them, happy to make any changes or close the PR it if it doesn't align with your vision. Thanks for making this integration!

---

_For details on the underlying detection method, see the [other PR](https://github.com/rccoleman/lmdirect/pull/33)._

# Solution

Added a binary_sensor to show the state of the water reservoir using the `problem` device class (see screenshots).

| Water Tank _Not_ Empty | Water Tank Empty |
| --- | --- |
|  image | image|

**Other changes:**
- Tests:
  - Fixed a bug where a new param `last_step` is being returned by HA (2021.11.5) was missing from the expected outcome causing the tests to fail
  - Added `__init__` into `custom_components` so pytest would find the local module properly
  - Added fixture in `conftest` that `pytest_homeassistant_custom_component==0.4.12` needed to enable loading custom integrations in tests
  - Added a requirements file to make it easier to get set up to run the tests locally, and in the future to help run them via Github Actions
- Added a gitignore to avoid committing pycache files

## Key decisions
1. Adding a `binary_sensor` rather than just an attribute on the Main switch: Figured many La Marzocco customers wouldn't have their machines plumbed and would find this useful and more easily discoverable for automations. For those with plumbed machines they can easily disable the sensor or not include it in your dashboard
2. Used the `device_class` `problem` to show the sensor: When the tank runs out of water it's something that needs to be actioned, so figured this status best mapped to the action you'd take from the sensor information. Also considered a generic On/Off and `moisture` (showed "Wet" as red in history as if it was a bad thing), but they didn't match as well.
3. The binary sensor is _only_ added for the Linea Mini, given I haven't been able to confirm if the same detection method works on the GS3.

## Testing
- Unit tests passing (we should add it to Github Actions 😄)
- Manually tested in HA `2021.11.5`

### CODE REVIEW

**Comment by mrvautin** [comment]
This is cool! Great work! Is the sensor binary? Like.. full.. full.. empty? Or is there a "running low" status?

**Comment by timclipsham** [comment]
Yep it's binary, with one state representing "water level higher than 'almost empty'" and the other "almost empty or less". When the water level goes below the higher contact (first picture), that opens the circuit and triggers a blue light on the front of the linea mini and with this change will update a sensor in HA to remind you to fill the tank.

| Water Tank | Contacts behind tank |
| --- | --- |
| image | image |

**Comment by mrvautin** [comment]
Ok cool. I wish LM made the "almost" empty trigger with more fat in it. Mine goes empty midway through pulling a shot on a regular basis.

**Comment by dhavalshreyas** [comment]
This sensor will be very helpful! Any reason this has not been merged yet?

**Comment by rccoleman** [comment]
After many months of procrastination and work obligations, I finally made new releases of the integration and underlying lmdirect package incorporating improvements to connection robustness and this reservoir detection support.  I confirmed that it works on my GS/3, so I added it to both GS/3 models as well.  It's available as a prerelease on the dev branch and in HACS (if you indicate that you want beta releases).  Please give it a try and I'll merge everything to master if there aren't any issues.

**Pull request merged**
